services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    WEM\PressFsyncBotBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,Event,Module}